apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: k8s-monitoring
      version: "3.5.6"
      sourceRef:
        kind: HelmRepository
        name: alloy
        namespace: flux-system
  values:

    # Define the destinations automatically set in the different volume depending on the type
    destinations:
    - name: prometheus-local
      type: prometheus
      url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
    - name: loki-local
      type: loki
      url: http://loki-write.observability.svc.cluster.local:3100

    # The logs collector. It is deployed as a DaemonSet and gathers Pod and Node logs
    alloy-logs:
      alloy:
        clustering:
          enabled: true
        mounts:
          dockercontainers: false
          varlog: false
      enabled: true
      extraConfig: |
        // Any arbitrary Alloy configuration can be placed here.
        logging {
          level  = "warn"
        }

    # A StatefulSet that scrapes metrics from sources like cAdvisor, Kubelet, and kube-state-metrics
    alloy-metrics:
      enabled: true

    # 1-replica Deployment to collect cluster events
    alloy-singleton:
      enabled: true

    cluster:
      name: homelab-alloy-cluster

    # The destination is automatically set from the destinations at the top of the config
    clusterMetrics:
      enabled: true

    # The destination is automatically set from the destinations at the top of the config
    clusterEvents:
      enabled: true

    # The destination is automatically set from the destinations at the top of the config
    podLogs:
      enabled: true
      gatherMethod: kubernetesApi
      labelsToKeep:
        - app_kubernetes_io_name
        - container
        - instance
        - job
        - level
        - namespace
        - service_name
        - service_namespace
        - deployment_environment
        - deployment_environment_name
      structuredMetadata:
        pod: pod
