---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: "0.3.13"
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: flux-system
  values:
    image:
      tag: stable
    env:
      - name: TZ
        value: Europe/Paris
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
