---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  values:
    nodeSelector:
      kubernetes.io/hostname: raspberrypi
    additionalVolumes:
      - hostPath:
          path: >-
            /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_6aaaa4186bc2ef11aad9c9138148b910-if00-port0
          type: CharDevice
        name: usb
    additionalMounts:
      - mountPath: /dev/ttyUSB0
        name: usb
