---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  values:
    nodeSelector:
      kubernetes.io/hostname: raspberrypi
    additionalVolumes:
      - hostPath:
          path: /dev/ttyUSB0
          type: CharDevice
        name: usb
    additionalMounts:
      - mountPath: /dev/ttyUSB0
        name: usb
