---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  values:
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      capabilities:
        add:
          - SYS_RAWIO
          - SYS_ADMIN
    nodeSelector:
      kubernetes.io/hostname: raspberrypi
    additionalVolumes:
      - hostPath:
          path: /dev/ttyUSB0
          type: CharDevice
        name: usb
    additionalMounts:
      - mountPath: /dev/ttyUSB0
        name: usb
    configuration:
      enabled: true
      templateConfig: |-
        # Load frontend themes from the themes folder
        frontend:
          themes: !include_dir_merge_named themes

        automation: !include automations.yaml
        script: !include scripts.yaml
        scene: !include scenes.yaml
        logger:
          default: info
          logs:
            homeassistant.core: debug
            homeassistant.components.zha: debug
            bellows.zigbee.application: debug
            bellows.ezsp: debug
            zigpy: debug
            zigpy_deconz.zigbee.application: debug
            zigpy_deconz.api: debug
            zigpy_xbee.zigbee.application: debug
            zigpy_xbee.api: debug
            zigpy_zigate: debug
            zigpy_znp: debug
            zhaquirks: debug
