apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-cnpg-cluster
  namespace: forgejo
spec:
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
  instances: 2
  storage:
    size: 1Gi

