apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.46.0"
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
  values:
    namespaceOverride: observability
    backend:
      replicas: 1
    deploymentMode: SimpleScalable
    gateway:
      enabled: true
    loki:
      auth_enabled: false
      ingester:
        chunk_encoding: snappy
      limits_config:
        allow_structured_metadata: true
        retention_period: 672h
        volume_enabled: true
      pattern_ingester:
        enabled: true
      querier:
        max_concurrent: 2
      schemaConfig:
        configs:
          - from: '2025-07-01'
            index:
              period: 24h
              prefix: loki_index_
            object_store: s3
            schema: v13
            store: tsdb
    lokiCanary:
      enabled: false
    minio:
      enabled: true
    read:
      replicas: 1
    sidecar:
      rules:
        logLevel: WARNING
    write:
      replicas: 2

    # Zero out replica counts of other deployment modes
		singleBinary:
			replicas: 0

		ingester:
			replicas: 0
		querier:
			replicas: 0
		queryFrontend:
			replicas: 0
		queryScheduler:
			replicas: 0
		distributor:
			replicas: 0
		compactor:
			replicas: 0
		indexGateway:
			replicas: 0
		bloomCompactor:
			replicas: 0
		bloomGateway:
			replicas: 0 
