apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.38.0"
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
  values:
    namespaceOverride: observability

    deploymentMode: SimpleScalable


    loki:
      commonConfig:
        replication_factor: 1
      auth_enabled: false
      resources:
        requests:
          cpu: 150m
          memory: 250Mi
        limits:
          cpu: 600m
          memory: 600Mi
      ingester:
        chunk_encoding: snappy
      limits_config:
        allow_structured_metadata: true
        retention_period: 672h
        volume_enabled: true
      pattern_ingester:
        enabled: true
      querier:
        max_concurrent: 2
      schemaConfig:
        configs:
          - from: '2025-07-01'
            index:
              period: 24h
              prefix: loki_index_
            object_store: s3
            schema: v13
            store: tsdb

    lokiCanary:
      enabled: false

    minio:
      enabled: true

    gateway:
      enabled: true

    backend:
      replicas: 1

    read:
      replicas: 1

    write:
      replicas: 1

    sidecar:
      rules:
        logLevel: WARNING

    test:
      enabled: false

    # Zero out replica counts of other deployment modes
    singleBinary:
      replicas: 0

    chunksCache:
      enabled: false

    resultsCache:
      enabled: false

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
